############################################################################
# The following is an minimal example of the compile and link commands
# needed on Perlmutter.  The Perlmutter build of the polyMPO stack followed 
# the build instructions in README.md - **no other configuration was tested**.
# 
# Using this Makefile on a different system is not advised as it will require 
# editing the paths in the first section **and** modifying the compile and link
# arguments.  This is not intended to be portable as there is no logic to
# detect/discover compilers and other system software.
############################################################################


###########################
## edit the following paths
###########################
FC=gfortran

CUDA_DIR=/opt/nvidia/hpc_sdk/Linux_x86_64/22.7/cuda/11.7/

MPI_DIR=/opt/cray/pe/mpich/8.1.25/ofi/gnu/9.1/
MPI_LIBS=${MPI_DIR}/lib/libmpifort_gnu_91.so ${MPI_DIR}/lib/libmpi_gnu_91.so

devRoot=/global/homes/y/yygong/develop

KOKKOS_DIR=${devRoot}/build-kokkos-login21-cuda/install/
KOKKOS_LIB_DIR=${KOKKOS_DIR}/lib64

OMEGAH_DIR=${devRoot}/build-omegah-login21-cuda/install/

ENGPAR_DIR=${devRoot}/build-engpar-login21-cuda/install/

PUMIPIC_DIR=${devRoot}/build-pumipic-login21-cuda/install/

CABANA_DIR=${devRoot}/build-cabana-login21-cuda/install/

POLYMPO_DIR=${devRoot}/buildPolyMPO-GPU/install

######################################################################################
## Dont't change the following unless you know exactly what you are doing...
## The following was generated from the CMake generated compile and link commands in
## a CUDA enabled build of polyMPO
######################################################################################
POLYMPO_LIBS=\
-L${CUDA_DIR}/targets/x86_64-linux/lib/stubs \
-L${CUDA_DIR}/targets/x86_64-linux/lib \
-Wl,-rpath,${CUDA_DIR}/lib64: \
${POLYMPO_DIR}/lib/libpolympo_fortran.a \
${POLYMPO_DIR}/lib/libpolyMpmTest-core.a \
-lm \
${PUMIPIC_DIR}/lib/libpumipic-core.a \
${PUMIPIC_DIR}/lib/libparticleStructs.a \
${PUMIPIC_DIR}/lib/libsupport.a \
${OMEGAH_DIR}/lib/libomega_h.a \
${KOKKOS_LIB_DIR}/libkokkoscontainers.a \
${KOKKOS_LIB_DIR}/libkokkoscore.a \
-lcuda \
-lcudart \
-ldl \
-lz \
${ENGPAR_DIR}/lib/libengpar.a \
${ENGPAR_DIR}/lib/libdiffusive.a \
${ENGPAR_DIR}/lib/libmultilevel.a \
${ENGPAR_DIR}/lib/libengpar_metrics.a \
${ENGPAR_DIR}/lib/libcoloring.a \
${ENGPAR_DIR}/lib/libagi.a \
${ENGPAR_DIR}/lib/libengpar_support.a \
${ENGPAR_DIR}/lib/libpcu.a \
${MPI_LIBS} \
-lcudadevrt \
-lcudart_static \
-lrt \
-lpthread \
-ldl \
-lstdc++

POLYMPO_COMPILE_FLAGS=\
-DFP64 \
-DKOKKOS_ENABLED \
-DLOCAL_ID_FTYPE=C_INT32_T \
-DLOCAL_ID_TYPE=int32_t \
-DPP_ENABLE_CAB \
-DPP_USE_CUDA \
-I${POLYMPO_DIR}/include \
-I${PUMIPIC_DIR}/include \
-I${KOKKOS_DIR}/include \
-I${CUDA_DIR}/include \
-I${CABANA_DIR}/include \
-I${MPI_DIR}/include \
-I${OMEGAH_DIR}/include \
-I${ENGPAR_DIR}/include

testFortranInit: testFortranInit.o
		${FC} testFortranInit.o -o testFortranInit ${POLYMPO_LIBS}

testFortranInit.o: testFortranInit.f90
		${FC} ${POLYMPO_COMPILE_FLAGS} -c testFortranInit.f90 -o testFortranInit.o
